# Generated by Django 5.2.8 on 2025-11-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(null=True)),
                ('request_body_size', models.IntegerField(default=0)),
                ('response_body_size', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_api_timesta_e9a667_idx'), models.Index(fields=['ip_address'], name='sensors_api_ip_addr_86f2b9_idx'), models.Index(fields=['status_code'], name='sensors_api_status__5d7f33_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('web_login', 'Web Login'), ('api_token', 'API Token'), ('web_access', 'Web Access')], max_length=20)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_aut_timesta_2acce3_idx'), models.Index(fields=['ip_address'], name='sensors_aut_ip_addr_28e2ee_idx'), models.Index(fields=['status'], name='sensors_aut_status_6a84bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ESP32ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_ip', models.GenericIPAddressField()),
                ('network_mode', models.CharField(max_length=16)),
                ('data_received', models.BooleanField(default=True)),
                ('sensors_included', models.JSONField()),
                ('payload_size', models.IntegerField()),
                ('processing_time_ms', models.IntegerField(null=True)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_esp_timesta_4fd89c_idx'), models.Index(fields=['device_ip'], name='sensors_esp_device__c15e5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FrontendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=10)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('component', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('error_stack', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_fro_timesta_004857_idx'), models.Index(fields=['level'], name='sensors_fro_level_736ff2_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('blocked_by', models.CharField(max_length=50)),
                ('violations_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['ip_address'], name='sensors_ipb_ip_addr_86dd75_idx'), models.Index(fields=['is_active'], name='sensors_ipb_is_acti_9f3daa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('rate_limit', 'Rate Limit Exceeded'), ('invalid_token', 'Invalid API Token'), ('malformed_request', 'Malformed Request'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('suspicious_pattern', 'Suspicious Pattern Detected'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('csrf_failed', 'CSRF Validation Failed')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_sec_timesta_5dffd1_idx'), models.Index(fields=['ip_address'], name='sensors_sec_ip_addr_c93035_idx'), models.Index(fields=['severity'], name='sensors_sec_severit_b7b6e6_idx'), models.Index(fields=['event_type'], name='sensors_sec_event_t_06e5fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10)),
                ('module', models.CharField(max_length=100)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_sys_timesta_bddbcb_idx'), models.Index(fields=['level'], name='sensors_sys_level_9615ee_idx')],
            },
        ),
    ]
