# Generated by Django 5.2.7 on 2025-10-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pm1', models.IntegerField()),
                ('pm25', models.IntegerField()),
                ('pm10', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('ch2o', models.IntegerField()),
                ('co', models.FloatField()),
                ('o3', models.FloatField()),
                ('no2', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=32)),
                ('network_mode', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ME4SO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField()),
                ('rawValue', models.IntegerField()),
                ('current_ua', models.FloatField()),
                ('so2_concentration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MR007',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField()),
                ('rawValue', models.IntegerField()),
                ('lel_concentration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ZE40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tvoc_ppb', models.FloatField()),
                ('tvoc_ppm', models.FloatField()),
                ('dac_voltage', models.FloatField()),
                ('dac_ppm', models.FloatField()),
                ('uart_data_valid', models.BooleanField()),
                ('analog_data_valid', models.BooleanField()),
            ],
        ),
    ]
