"""
Django settings for smartsensors_django project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Import centralized configuration
sys.path.insert(0, str(BASE_DIR))
try:
    from config import CONFIG
    print("✅ Loaded configuration from config.py")
except ImportError:
    print("⚠️  Warning: config.py not found. Using default settings.")
    CONFIG = {
        'SECRET_KEY': 'django-insecure-@z@5#rv!q6lli#lctg2vjvjw7w=2g3*i1ii9v5+792lpt2o#dw',
        'DEBUG_MODE': True,
        'ALLOWED_HOSTS': ['*'],
        'CORS_ALLOWED_ORIGINS': ['http://localhost:5173', 'http://127.0.0.1:5173'],
        'CORS_ALLOW_ALL_ORIGINS': True,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONFIG.get('SECRET_KEY', 'django-insecure-@z@5#rv!q6lli#lctg2vjvjw7w=2g3*i1ii9v5+792lpt2o#dw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CONFIG.get('DEBUG_MODE', True)

# Compute ALLOWED_HOSTS. If the server is configured to bind to 0.0.0.0
# and the configured DJANGO_URL is inside a private 192.168.1.0/24 network,
# expand ALLOWED_HOSTS to include all addresses in that /24 so LAN clients
# can access the Django server without requiring manual host entries.
try:
    django_url = CONFIG.get('DJANGO_URL', '')
    parsed = urlparse(django_url)
    host = parsed.hostname
except Exception:
    host = None

if CONFIG.get('DJANGO_HOST') == '0.0.0.0' and host and host.startswith('192.168.'):
    # Derive /24 prefix (e.g. 192.168.1.) and allow .1 - .254
    parts = host.split('.')
    if len(parts) >= 3:
        prefix = '.'.join(parts[:3]) + '.'
        generated_hosts = [prefix + str(i) for i in range(1, 255)]
        # include localhost variants as well
        ALLOWED_HOSTS = ['localhost', '127.0.0.1'] + generated_hosts
    else:
        ALLOWED_HOSTS = CONFIG.get('ALLOWED_HOSTS', ['*'])
else:
    ALLOWED_HOSTS = CONFIG.get('ALLOWED_HOSTS', ['*'])

# CORS Configuration
CORS_ALLOWED_ORIGINS = CONFIG.get('CORS_ALLOWED_ORIGINS', [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = CONFIG.get('CORS_ALLOW_ALL_ORIGINS', True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'sensors',
    # 'django_jalali',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'sensors.middleware.SecurityLoggingMiddleware',
    'sensors.middleware.SuspiciousPatternMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartsensors_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartsensors_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smartsensors',
        'USER': 'sensoradmin',
        'PASSWORD': 'sensoradmin123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
